#!/bin/bash


red="\033[00;31m"
green="\033[00;32m"
yellow="\033[00;33m"
blue="\033[00;34m"
purple="\033[00;35m"
cyan="\033[00;36m"

reset="\033[00m"

for gitdir in `find . $i -name .git` ; do
( 	
	working=$(dirname $gitdir)
	STAT="$green updating: $working/$reset"
	echo " "
	echo "------------------------------"
	echo -e "$STAT"
	echo "------------------------------"
	cd $working
	git pull
)
done

